import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-health-plan-vendor-guarantee-claims-audit",
  "engine": "recovery",
  "title": "Health Plan Vendor Guarantee & Claims Audit",
  "shortTitle": "Health Plan Vendor Guarantee and Claims Audit",
  "tagline": "Quantify, recover, and prevent financial leakage through health plan vendor guarantee & claims audit",
  "industry": "Employer Health Plan Assurance",
  "uiPort": 4640,
  "apiPort": 5640,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Health Plan Vendor Guarantee & Claims Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "receivedCredits",
    "expectedKey": "earnedCredits",
    "actualLabel": "Received Performance Credits",
    "expectedLabel": "Calculated Guarantee Credits",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Health Plan Vendor Guarantee & Claims Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("vendor-agreement-library","HPV01","Vendor agreement library","Execute vendor agreement library using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed vendor agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Vendor agreement library Reference","text","HPV01-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("member-eligibility","HPV02","Member eligibility","Execute member eligibility using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed member eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Member eligibility Reference","text","HPV02-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("claim-encounter-ingestion","HPV03","Claim encounter ingestion","Execute claim encounter ingestion using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed claim encounter ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Claim encounter ingestion Reference","text","HPV03-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("administrative-fee-validation","HPV04","Administrative fee validation","Execute administrative fee validation using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed administrative fee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Administrative fee validation Reference","text","HPV04-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("discount-guarantee-calculation","HPV05","Discount guarantee calculation","Execute discount guarantee calculation using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed discount guarantee calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Discount guarantee calculation Reference","text","HPV05-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("rebate-guarantee-validation","HPV06","Rebate guarantee validation","Execute rebate guarantee validation using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed rebate guarantee validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Rebate guarantee validation Reference","text","HPV06-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("service-level-measurement","HPV07","Service-level measurement","Execute service-level measurement using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed service-level measurement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Service-level measurement Reference","text","HPV07-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("implementation-milestones","HPV08","Implementation milestones","Execute implementation milestones using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed implementation milestones decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Implementation milestones Reference","text","HPV08-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("clinical-outcome-guarantee","HPV09","Clinical outcome guarantee","Execute clinical outcome guarantee using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed clinical outcome guarantee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Clinical outcome guarantee Reference","text","HPV09-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("engagement-guarantee","HPV10","Engagement guarantee","Execute engagement guarantee using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed engagement guarantee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Engagement guarantee Reference","text","HPV10-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("data-delivery-sla","HPV11","Data delivery SLA","Execute data delivery sla using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed data delivery sla decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Data delivery SLA Reference","text","HPV11-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("performance-credit-calculation","HPV12","Performance credit calculation","Execute performance credit calculation using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed performance credit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Performance credit calculation Reference","text","HPV12-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("vendor-evidence-request","HPV13","Vendor evidence request","Execute vendor evidence request using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed vendor evidence request decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Vendor evidence request Reference","text","HPV13-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("settlement-negotiation-workflow","HPV14","Settlement negotiation workflow","Execute settlement negotiation workflow using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed settlement negotiation workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Settlement negotiation workflow Reference","text","HPV14-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]}),
feature("credit-outcome-reconciliation","HPV15","Credit outcome reconciliation","Execute credit outcome reconciliation using health plan, PBM, behavioral health, navigation and point-solution agreements, member eligibility, claims, encounters, administrative fees, discount and rebate guarantees, service levels, outcomes, engagement, data SLAs, and credits.","Produce a governed credit outcome reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Employer / Health Vendor","text","Employer / Health Vendor · Standard Case"],["caseReference","Credit outcome reconciliation Reference","text","HPV15-2026-001"],["receivedCredits","Received Performance Credits","currency",1326500],["earnedCredits","Calculated Guarantee Credits","currency",1565270],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"receivedCredits",subjects:["Vendor agreement library case","Member eligibility case","Claim encounter ingestion case","Administrative fee validation case","Discount guarantee calculation case"]})
]);
